accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('register/', views.register_page, name='register_page'),
    path('login/', views.login_page, name='login_page'),
    path('logout/', views.logout_page, name='logout_page'),
]

hack/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls')),
    path('', include('vacancies.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vacancies/urls.py
from django.urls import path
from . import views


app_name = 'vacancies'
urlpatterns = [
    path('', views.vacancy_list, name='vacancy_list'),
    path('<int:id>/', views.vacancy_detail, name='vacancy_detail'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" class="page">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <meta name="theme-color" content="#111111">
      <title>Мос Волонтёр</title>
      <link rel="preload" href="{% static 'accounts/register_page/fonts/MullerRegular.woff2' %}" as="font" type="font/woff2" crossorigin>
      <link rel="preload" href="{% static 'accounts/register_page/fonts/Rubik-Bold.woff2' %}" as="font" type="font/woff2" crossorigin>
      <link rel="preload" href="{% static 'accounts/register_page/fonts/Rubik-Medium.woff2' %}" as="font" type="font/woff2" crossorigin>
      <link rel="preload" href="{% static 'accounts/register_page/fonts/Rubik-Regular.woff2' %}" as="font" type="font/woff2" crossorigin>
      <link rel="stylesheet" href="{% static 'accounts/register_page/css/vendor.css' %}">
      <link rel="stylesheet" href="{% static 'accounts/register_page/css/main.css' %}">

      {% block styles %}
      {% endblock styles %}
   </head>
   <body class="page__body">
      <div class="site-container">
         {% include 'header.html' %}
          
         {% if messages %}
         <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
         </ul>
         {% endif %}

         <main class="main">
            {% block content %}
            {% endblock content %}
         </main>
         {% include 'footer.html' %}
      </div>

      <!-- JavaScript Bundle with Popper --><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
   </body>
</html>

templates/footer.html
<footer class="footer">
    <div class="container"></div>
</footer>

templates/header.html
{% load static %}
<header class="header">
    <div class="container header__container">
       <a href="{% url 'vacancies:vacancy_list' %}" class="logo"><img loading="lazy" src="{% static 'logo.svg' %}" class="image" width="83" height="32" alt="Логотип RoboSchool"></a>
       <nav class="nav" title="Главное меню" data-menu>
          <ul class="list-reset nav__list">
             {% if not request.user.is_authenticated %}
             <li class="nav__item"><a href="{% url 'accounts:login_page' %}" class="nav__link" data-menu-item data-scroll>Войти</a></li>
             {% else %}
             <li class="nav__item"><a href="{% url 'accounts:logout_page' %}" class="nav__link" data-menu-item data-scroll>Выйти</a></li>
             {% endif %}
          </ul>
          <button class="btn-reset burger-close" aria-label="Закрыть меню" data-menu-close></button>
       </nav>
    </div>
    <hr class="hr__setting">
</header>